/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F44xx__driver.h"
#include "STM32F44xxgpio__driver.h"
#include "STM32F44xxSPI__driver.h"
#include <stdlib.h>
#include <string.h>

/*
 * Create a function for sending out data using
 * the blocking method
 */

int main(void)
{
    char* TxBuffer = "Hello World";
    gpio_handle_t SPI_Pin;
    memset(&SPI_Pin,0,sizeof(gpio_handle_t));

    //Enable peripheral Clock for GPIO pins
    GPIO_PeriClockControl(GPIOA, ENABLE);

    //Set up the SPI1 pins
    SPI_Pin.gpioReg = GPIOA;
    SPI_Pin.gpioConfigure.MODE = GPIO_MODE_ALFN;
    SPI_Pin.gpioConfigure.ALTF = AF5;
    SPI_Pin.gpioConfigure.OSPEED = GPIO_LOW_SPEED;
    SPI_Pin.gpioConfigure.PUPD = GPIO_NO_PUPD;

    //Set up the MOSI pin
    SPI_Pin.gpioConfigure.pinNumber = GPIO_PIN_NO_7;
    gpioInit(&SPI_Pin);
    //Set up the clock pin
    SPI_Pin.gpioConfigure.pinNumber = GPIO_PIN_NO_5;
    gpioInit(&SPI_Pin);
    //Set up the NSS pin
    SPI_Pin.gpioConfigure.pinNumber = GPIO_PIN_NO_4;
    gpioInit(&SPI_Pin);

    SPI_Handle_t theSpi;
    memset(&theSpi,0,sizeof(SPI_Handle_t));

    //Enable the peripheral clock for SPI peripheral
    SPI_PeriClockControl(SPI1, ENABLE);
    //Initialize the SPI peripheral
    theSpi.pSPIx = SPI1;
    theSpi.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    theSpi.SPIConfig.SPI_CPHA = SPI_CPHA1;
    theSpi.SPIConfig.SPI_CPOL = SPI_CPOL0;
    theSpi.SPIConfig.SPI_DFF = DFF8;
    theSpi.SPIConfig.SPI_DeviceMode = MASTER;
    theSpi.SPIConfig.SPI_SSM = SSM_HW;
    theSpi.SPIConfig.SPI_SclkSpeed = SPI_CLK_SPEED_DIV2;

    spiInit(&theSpi);
    setSSOE(SPI1, ENABLE);
    spiEnable(SPI1, ENABLE);

    SPI_SendData(SPI1, (uint8_t*)TxBuffer, strlen(TxBuffer)+1);

    spiEnable(SPI1, DISABLE);
}
